### ISSUE TITLE
Applying Color Temperature to Image

### ISSUE THREAD

**Issue by jamesd79** [tannerhelland/tannerhelland-dot-com#1]
I read your excellent article on color temperature at: 

https://tannerhelland.com/2012/09/18/convert-temperature-rgb-algorithm-code.html

I'd like to use the same technique in a project I'm working on, but it was not clear to me how to apply a given color temperature to an image pixel. I get how to compute the RGB for a given temperature in Kelvin, but how do you combine that with the input image pixel RGB to get the output color?

It would be great if you could add that to your article, or just pointing me in the right direction in terms of where I can find it in your code?

Thank you!

**Comment by jamesd79** [comment]
Nevermind, I found the code at:

https://github.com/tannerhelland/PhotoDemon/blob/master/Forms/Adjustments_Color_Temperature.frm

It would be great to add some pseudo code to the article on this, but I can figure it out from the code. Thanks.

**Comment by monktastic** [comment]
Would be good to reopen this issue. The article is confusing when it says:

> On the left is the original shot; on the right, a color temperature adjustment using the code above.

It doesn't use the code "above."
