### ISSUE TITLE
Rust port of the temperature to rgb conversion

### ISSUE THREAD

**Issue by m-lima** [tannerhelland/tannerhelland-dot-com#2]
Hi,

Thanks for the great article at [How to Convert Temperature (K) to RGB: Algorithm and Sample Code](https://tannerhelland.com/2012/09/18/convert-temperature-rgb-algorithm-code.html)
I needed to do such a conversion in Rust and stumbled upon your article. With that, I am sharing with you the port to rust, in case other users are interested: https://github.com/m-lima/temperagb

Cheers

**Comment by tannerhelland** [comment]
Thank you for letting me know, @m-lima!  I've added a link to your work on the original article.
