### ISSUE TITLE
Broken donate link

### ISSUE THREAD

**Issue by Aircoookie** [tannerhelland/tannerhelland-dot-com#5]
Hey!
I would like to make a one-time donation to thank you for your awesome work on the Kelvin -> RGB algorithm.
Unfortunately, the https://tannerhelland.com/donate/ link at the bottom of the page 404s.

**Comment by tannerhelland** [comment]
How embarrassing! 🤦‍♂️   Thank you so much for notifying me, @Aircoookie.  The link is all fixed now.  

(And thank you in advance for the donation 🙏 )
