### ISSUE TITLE
RGB color from light K temperature - Port to C++ for Unreal Engine

### ISSUE THREAD

**Issue by byValle** [tannerhelland/tannerhelland-dot-com#7]
Hi Tanner,

First of all, your work is incredible, congratulations.

Second, I would like to share with you the port I've made of your Kelvin to RGB algorithm to C++ for Unreal Engine:
[RGB color from light K temperature - Port to C++ for Unreal Engine](https://gist.github.com/byValle/b81391dcb2edaef9c651132ab3f123a9
)

I hope it's useful for someone!

Cheers

**Comment by tannerhelland** [comment]
Thank you, @byValle ! Your work is now linked from the original article: https://tannerhelland.com/2012/09/18/convert-temperature-rgb-algorithm-code.html
